-- CTE (COMMON EXPRESSION TABLE)

--SELECT * FROM employee


WITH EMPLOYEE_COUNT
AS
(	SELECT DEPARTMENT, COUNT(ID) AS EMP_COUNT
	FROM employee
	GROUP BY department
)
SELECT * 
FROM employee
JOIN EMPLOYEE_COUNT
ON EMPLOYEE.ID = EMPLOYEE_COUNT.EMP_COUNT
ORDER BY EMP_COUNT
