USE KUDVENKAT;

--CREATE TABLE GENDER
--(
--	ID INT IDENTITY(1,1),
--	NAME VARCHAR(20) NOT NULL
--)

--ALTER TABLE GENDER
--ADD CONSTRAINT PK_ID PRIMARY KEY (ID);

--CREATE TABLE EMPLOYEE
--(
--	ID INT PRIMARY KEY IDENTITY(1,1),
--	NAME VARCHAR(100) NOT NULL,
--	GENDER INT FOREIGN KEY REFERENCES GENDER(ID) ON DELETE CASCADE ON UPDATE SET NULL
--)

SELECT * FROM GENDER
SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE(NAME,GENDER) VALUES('AR RAHMAN',1)

--CREATE TABLE #IDENTITY_TBL
--(
--	ID INT IDENTITY(1,1),
--	NAME VARCHAR
--)

--ALTER TABLE #IDENTITY_TBL
--ALTER COLUMN NAME VARCHAR(MAX)

SELECT * FROM #IDENTITY_TBL;

--SET IDENTITY_INSERT #IDENTITY_TBL OFF;

SELECT SCOPE_IDENTITY()
SELECT @@IDENTITY
SELECT IDENT_CURRENT('#IDENTITY_TBL')

INSERT INTO #IDENTITY_TBL VALUES('AANDIA');




