--	SELF JOIN
--DROP TABLE IF EXISTS #EMP 
--CREATE TABLE #EMP (
--    ID INT PRIMARY KEY IDENTITY(1,1),
--    NAME VARCHAR(100),
--	MANAGER_ID INT
--);

--INSERT INTO #EMP(NAME) VALUES('AZIZ'),('RAHMAN'),('NADIM'),('SHAMIM'),('ABDUL'),('PRAKASH')


--UPDATE #EMP
--SET MANAGER_ID = 1
--WHERE ID = 6

--SELECT * FROM #EMP

SELECT E.NAME AS EMPLOYEE, M.NAME AS MANAGER
FROM #EMP E
LEFT JOIN #EMP M
ON E.MANAGER_ID = M.ID


SELECT E.NAME AS EMPLOYEE, M.NAME AS MANAGER
FROM #EMP E
RIGHT JOIN #EMP M
ON E.MANAGER_ID = M.ID

